FROM gcc:13.2 as bef93
SHELL ["/bin/bash", "-c"]
RUN git clone https://github.com/catseye/Befunge-93/ bef93
WORKDIR /bef93
RUN make

FROM gcc:13.2
SHELL ["/bin/bash", "-c"]
COPY --from=bef93 /bef93/bin/bef /bin/
COPY . /app
WORKDIR /app

CMD ["bef", "-q", "app/main.bf"]
