---
- name: Update OS
  apt:
    update_cache: yes

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - git
    - gnupg2
    - docker.io
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - python3-dev
    - python3-apt
    - kubelet


- name: Set timezone
  timezone:
    name: Europe/Paris
